# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:28
from __future__ import unicode_literals

import bammmotif.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DbParameter',
            fields=[
                ('param_id', models.SmallIntegerField(db_column='param_ID', primary_key=True, serialize=False)),
                ('data_source', models.CharField(max_length=12)),
                ('species', models.CharField(max_length=12)),
                ('experiment', models.CharField(max_length=20)),
                ('base_dir', models.CharField(max_length=50)),
                ('motif_init_file_format', models.CharField(max_length=12)),
                ('alphabet', models.CharField(max_length=12)),
                ('reversecomp', models.IntegerField(db_column='reverseComp')),
                ('modelorder', models.IntegerField(db_column='modelOrder')),
                ('extend_1', models.IntegerField()),
                ('extend_2', models.IntegerField()),
                ('bgmodelorder', models.IntegerField(db_column='bgModelOrder')),
                ('em', models.IntegerField(db_column='EM')),
                ('maxemiterations', models.BigIntegerField(db_column='maxEMIterations')),
                ('epsilon', models.FloatField()),
                ('fdr', models.IntegerField(db_column='FDR')),
                ('mfold', models.IntegerField(db_column='mFold')),
                ('cvfold', models.IntegerField(db_column='cvFold')),
                ('samplingorder', models.IntegerField(db_column='samplingOrder')),
                ('savelogodds', models.IntegerField(db_column='saveLogOdds')),
                ('cgs', models.IntegerField(db_column='CGS')),
                ('maxcgsiterations', models.BigIntegerField(db_column='maxCGSIterations')),
                ('noalphasampling', models.IntegerField(db_column='noAlphaSampling')),
            ],
            options={
                'db_table': 'db_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbTable',
            fields=[
                ('db_public_id', models.SmallIntegerField(db_column='db_public_ID', primary_key=True, serialize=False)),
                ('laboratory', models.CharField(max_length=12)),
                ('cell_line', models.CharField(max_length=24)),
                ('cell_line_1', models.CharField(max_length=12)),
                ('cell_line_2', models.CharField(max_length=12)),
                ('protein_name', models.CharField(max_length=20)),
                ('pos_seq_file', models.CharField(max_length=120)),
                ('neg_seq_file', models.CharField(blank=True, max_length=80, null=True)),
                ('intensity_file', models.CharField(blank=True, max_length=80, null=True)),
                ('motif_init_file', models.CharField(max_length=120)),
                ('result_location', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'db_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(blank=True, choices=[('Not_Initialized', 'Not_Initialized'), ('Data_Upload', 'Data_Upload'), ('Parameter_Setting', 'Parameter_Setting'), ('Ready_to_Submit', 'Ready_to_submit'), ('Submitted', 'Submitted'), ('Queueing', 'Queueing'), ('Running', 'Running'), ('Finished', 'Finished'), ('Crashed', 'Crashed')], default='Not_Initialized', max_length=255, null=True)),
                ('Input_Sequences', models.FileField(null=True, upload_to=bammmotif.models.job_directory_path)),
                ('Background_Sequences', models.FileField(blank=True, null=True, upload_to=bammmotif.models.job_directory_path)),
                ('Intensity_File', models.FileField(blank=True, null=True, upload_to=bammmotif.models.job_directory_path)),
                ('Motif_Initialization', models.CharField(choices=[('Custom File', 'Custom File'), ('PeNGmotif', 'PeNGmotif'), ('DB File', 'DB File')], default='Custom File', max_length=255)),
                ('Motif_InitFile', models.FileField(blank=True, null=True, upload_to=bammmotif.models.job_directory_path)),
                ('Motif_Init_File_Format', models.CharField(choices=[('BindingSites', 'BindingSites'), ('PWM', 'PWM'), ('BaMM', 'BaMM')], default='BindingSites', max_length=255)),
                ('model_Order', models.PositiveSmallIntegerField(default=3)),
                ('reverse_Complement', models.BooleanField(default=False)),
                ('extend_1', models.PositiveSmallIntegerField(default=0)),
                ('extend_2', models.PositiveSmallIntegerField(default=0)),
                ('FDR', models.BooleanField(default=False)),
                ('m_Fold', models.IntegerField(default=100)),
                ('cv_Fold', models.IntegerField(default=5)),
                ('sampling_Order', models.PositiveSmallIntegerField(default=2)),
                ('save_LogOdds', models.BooleanField(default=True)),
                ('CGS', models.BooleanField(default=False)),
                ('max_CGS_Iterations', models.BigIntegerField(default=1000000.0)),
                ('no_Alpha_Sampling', models.BooleanField(default=True)),
                ('EM', models.BooleanField(default=True)),
                ('epsilon', models.DecimalField(decimal_places=4, default=0.001, max_digits=5)),
                ('max_EM_Iterations', models.BigIntegerField(default=1000000.0)),
                ('no_Alpha_Optimization', models.BooleanField(default=True)),
                ('alphabet', models.CharField(choices=[('STANDARD', 'STANDARD'), ('METHYLIC', 'METHYLIC'), ('HYDROXYMETHYLIC', 'HYDROXYMETHYLIC'), ('EXTENDED', 'EXTENDED')], default='STANDARD', max_length=255)),
                ('background_Order', models.PositiveSmallIntegerField(default=2)),
                ('verbose', models.BooleanField(default=True)),
                ('save_BaMMs', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
