# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num_motifs',
            field=models.IntegerField(default=1),
        ),
    ]
