# Generated by Django 2.0.3 on 2018-03-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengjob',
            name='strand',
            field=models.CharField(choices=[('PLUS', 'PLUS'), ('BOTH', 'BOTH')], default='BOTH', max_length=5),
        ),
    ]
