# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0002_job_num_motifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='q_value',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=3),
        ),
    ]
