# Generated by Django 2.0.3 on 2018-03-08 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0002_auto_20180308_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bammmotif.JobInfo')),
            ],
        ),
    ]
