# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0003_job_q_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='FDR',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Motif_Init_File_Format',
            field=models.CharField(choices=[('BindingSites', 'BindingSites'), ('PWM', 'PWM'), ('BaMM', 'BaMM')], default='PWM', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='Motif_Initialization',
            field=models.CharField(choices=[('Custom File', 'Custom File'), ('PEnGmotif', 'PEnGmotif'), ('DB File', 'DB File')], default='PEnGmotif', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='extend_1',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='extend_2',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='m_Fold',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='job',
            name='model_Order',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='reverse_Complement',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('data uploaded', 'data uploaded'), ('submitted', 'submitted')], default='not initialized', max_length=255, null=True),
        ),
    ]
