# Generated by Django 2.0.3 on 2018-03-08 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0003_jobsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
