# Generated by Django 2.0.3 on 2018-03-29 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0004_auto_20180308_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsession',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
