# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0004_auto_20170213_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
