# Generated by Django 2.0.3 on 2018-03-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0005_jobsession_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='has_input',
            field=models.BooleanField(default=True),
        ),
    ]
