# Generated by Django 2.0.3 on 2018-03-30 20:42

import bammmotif.utils.misc
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0005_jobsession_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneStepBaMMJob',
            fields=[
                ('meta_job', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bammmotif.JobInfo')),
                ('n_threads', models.IntegerField(default=4)),
                ('Input_Sequences', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/media/'), upload_to=bammmotif.utils.misc.job_upload_to_input)),
                ('Background_Sequences', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/media/'), upload_to=bammmotif.utils.misc.job_upload_to_input)),
                ('num_motifs', models.IntegerField(default=1)),
                ('reverse_Complement', models.BooleanField(default=True)),
                ('background_Order', models.PositiveSmallIntegerField(default=2)),
                ('meme_output', models.CharField(default='out.meme', max_length=150)),
                ('json_output', models.CharField(default='out.json', max_length=150)),
                ('temp_dir', models.CharField(default='temp', max_length=100, null=True)),
                ('pattern_length', models.IntegerField(default=10)),
                ('zscore_threshold', models.FloatField(default=10)),
                ('count_threshold', models.IntegerField(default=5)),
                ('objective_function', models.CharField(choices=[('LOGPVAL', 'LOGPVAL'), ('MUTUAL_INFO', 'MUTUAL_INFO'), ('ENRICHMENT', 'ENRICHMENT')], default='MUTUAL_INFO', max_length=50)),
                ('enrich_pseudocount_factor', models.FloatField(default=0.005)),
                ('no_em', models.BooleanField(default=False)),
                ('em_saturation_threshold', models.FloatField(default=10000.0)),
                ('em_threshold', models.FloatField(default=0.08)),
                ('em_max_iterations', models.IntegerField(default=20)),
                ('no_merging', models.BooleanField(default=False)),
                ('bit_factor_threshold', models.FloatField(default=0.4)),
                ('use_default_pwm', models.BooleanField(default=False)),
                ('pwm_pseudo_counts', models.IntegerField(default=10)),
                ('silent', models.BooleanField(default=True)),
                ('max_refined_motifs', models.IntegerField(default=3)),
                ('Motif_Initialization', models.CharField(choices=[('CustomFile', 'CustomFile'), ('PEnGmotif', 'PEnGmotif'), ('DBFile', 'DBFile')], default='PEnGmotif', max_length=255)),
                ('Motif_InitFile', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/media/'), upload_to=bammmotif.utils.misc.job_upload_to_input)),
                ('Motif_Init_File_Format', models.CharField(choices=[('BindingSites', 'BindingSites'), ('PWM', 'PWM'), ('BaMM', 'BaMM')], default='PWM', max_length=255)),
                ('model_order', models.PositiveSmallIntegerField(default=4)),
                ('extend', models.PositiveSmallIntegerField(default=0)),
                ('FDR', models.BooleanField(default=True)),
                ('m_Fold', models.IntegerField(default=10)),
                ('sampling_Order', models.PositiveSmallIntegerField(default=2)),
                ('EM', models.BooleanField(default=True)),
                ('score_Seqset', models.BooleanField(default=True)),
                ('score_Cutoff', models.FloatField(default=0.1)),
                ('bgModel_File', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/media/'), upload_to=bammmotif.utils.misc.job_upload_to_input)),
                ('verbose', models.BooleanField(default=True)),
                ('MMcompare', models.BooleanField(default=False)),
                ('p_value_cutoff', models.DecimalField(decimal_places=2, default=0.01, max_digits=3)),
                ('motif_db', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bammmotif.MotifDatabase')),
            ],
        ),
    ]
