# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0005_job_job_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChIPseq',
            fields=[
                ('db_public_id', models.SmallIntegerField(db_column='db_public_ID', primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('lab', models.CharField(max_length=12)),
                ('grant', models.CharField(max_length=12)),
                ('cell_type', models.CharField(max_length=12)),
                ('target_name', models.CharField(max_length=12)),
                ('ensembl_target_id', models.CharField(max_length=15)),
                ('treatment', models.CharField(max_length=25)),
                ('protocol', models.CharField(max_length=15)),
                ('pos_seq_file', models.CharField(max_length=120)),
                ('motif_init_file', models.CharField(max_length=120)),
                ('result_location', models.CharField(max_length=80)),
            ],
            options={
                'managed': False,
                'db_table': 'db_table',
            },
        ),
        migrations.CreateModel(
            name='Motifs',
            fields=[
                ('motif_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iupac', models.CharField(blank=True, max_length=50, null=True)),
                ('job_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('db_matches', models.ManyToManyField(to='bammmotif.ChIPseq')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='db_match_bit_factor',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=3),
        ),
        migrations.AddField(
            model_name='motifs',
            name='parent_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bammmotif.Job'),
        ),
    ]
