# Generated by Django 2.0.3 on 2018-04-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0006_onestepbammjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onestepbammjob',
            name='model_order',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='onestepbammjob',
            name='score_Cutoff',
            field=models.FloatField(default=0.01),
        ),
    ]
