# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0006_auto_20170320_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='motifs',
            name='auc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motifs',
            name='occurrence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
