# Generated by Django 2.0.3 on 2018-04-01 18:34

import bammmotif.utils.misc
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0007_auto_20180401_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onestepbammjob',
            name='Background_Sequences',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/media/'), upload_to=bammmotif.utils.misc.job_upload_to_input, validators=[bammmotif.utils.misc.file_size_validator]),
        ),
        migrations.AlterField(
            model_name='onestepbammjob',
            name='Input_Sequences',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/media/'), upload_to=bammmotif.utils.misc.job_upload_to_input, validators=[bammmotif.utils.misc.file_size_validator]),
        ),
    ]
