# Generated by Django 2.0.3 on 2018-04-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0008_auto_20180401_1834'),
        ('bammmotif', '0006_jobinfo_has_input'),
    ]

    operations = [
    ]
