# Generated by Django 2.0.3 on 2018-04-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0009_merge_20180401_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengjob',
            name='strand',
        ),
        migrations.AddField(
            model_name='pengjob',
            name='reverse_Complement',
            field=models.BooleanField(default=True),
        ),
    ]
