# Generated by Django 2.0.3 on 2018-04-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0010_auto_20180402_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmcomparejob',
            old_name='p_value_cutoff',
            new_name='e_value_cutoff',
        ),
        migrations.AlterField(
            model_name='mmcomparejob',
            name='Motif_Init_File_Format',
            field=models.CharField(choices=[('MEME', 'MEME'), ('BaMM', 'BaMM')], default='MEME', max_length=255),
        ),
    ]
