# Generated by Django 2.0.3 on 2018-04-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0011_auto_20180403_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bammjob',
            old_name='p_value_cutoff',
            new_name='e_value_cutoff',
        ),
        migrations.RemoveField(
            model_name='onestepbammjob',
            name='p_value_cutoff',
        ),
        migrations.AddField(
            model_name='onestepbammjob',
            name='e_value_cutoff',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=3),
        ),
    ]
