# Generated by Django 2.0.3 on 2018-04-04 12:05

import bammmotif.mmcompare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0012_auto_20180404_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmcomparejob',
            name='Motif_InitFile',
            field=models.FileField(null=True, upload_to=bammmotif.mmcompare.models.job_directory_path_motif),
        ),
    ]
