# Generated by Django 2.0.3 on 2018-04-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0013_auto_20180404_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bammscanjob',
            name='Motif_Init_File_Format',
            field=models.CharField(choices=[('MEME', 'MEME'), ('BaMM', 'BaMM')], default='PWM', max_length=255),
        ),
    ]
