# Generated by Django 2.0.3 on 2018-04-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0014_auto_20180404_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bammscanjob',
            old_name='p_value_cutoff',
            new_name='e_value_cutoff',
        ),
    ]
