# Generated by Django 2.0.3 on 2018-04-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0016_auto_20180404_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bammscanjob',
            name='score_Cutoff',
            field=models.FloatField(default=0.001),
        ),
    ]
