# Generated by Django 2.0.3 on 2018-04-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0017_auto_20180404_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onestepbammjob',
            name='MMcompare',
            field=models.BooleanField(default=True),
        ),
    ]
