# Generated by Django 2.0.3 on 2018-04-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0018_auto_20180405_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onestepbammjob',
            name='json_output',
        ),
        migrations.RemoveField(
            model_name='onestepbammjob',
            name='meme_output',
        ),
    ]
