# Generated by Django 2.0.3 on 2018-04-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0019_auto_20180405_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengjob',
            name='json_output',
        ),
        migrations.RemoveField(
            model_name='pengjob',
            name='meme_output',
        ),
    ]
