# Generated by Django 2.0.3 on 2018-04-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0022_auto_20180406_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengjob',
            name='n_threads',
            field=models.IntegerField(default=4),
        ),
    ]
