# Generated by Django 2.0.3 on 2018-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0023_auto_20180407_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bammjob',
            name='MMcompare',
            field=models.BooleanField(default=True),
        ),
    ]
