# Generated by Django 2.0.3 on 2018-04-16 08:36

import bammmotif.models.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0024_auto_20180407_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipseq',
            name='cell_types',
            field=bammmotif.models.custom_fields.SeparatedValuesField(null=True),
        ),
        migrations.AddField(
            model_name='chipseq',
            name='details_given',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chipseq',
            name='species',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
