# Generated by Django 2.0.3 on 2018-04-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0024_auto_20180407_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengjob',
            name='n_threads',
        ),
    ]
