# Generated by Django 2.0.3 on 2018-04-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0025_remove_pengjob_n_threads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onestepbammjob',
            name='n_threads',
            field=models.IntegerField(default=2),
        ),
    ]
