# Generated by Django 2.0.3 on 2018-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0027_remove_onestepbammjob_n_threads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bammjob',
            name='e_value_cutoff',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
