# Generated by Django 2.0.3 on 2018-04-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0028_auto_20180416_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bammjob',
            name='model_order',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='onestepbammjob',
            name='e_value_cutoff',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
