# Generated by Django 2.0.3 on 2018-04-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0029_auto_20180416_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='motifs',
            name='m_aurrc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
