# Generated by Django 2.0.3 on 2018-04-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0032_auto_20180417_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bammjob',
            name='score_Cutoff',
            field=models.FloatField(default=0.001),
        ),
        migrations.AlterField(
            model_name='onestepbammjob',
            name='score_Cutoff',
            field=models.FloatField(default=0.001),
        ),
    ]
