# Generated by Django 2.0.3 on 2018-04-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0025_auto_20180416_0836'),
        ('bammmotif', '0033_auto_20180417_1558'),
    ]

    operations = [
    ]
