# Generated by Django 2.0.3 on 2018-04-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0034_merge_20180417_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmcomparejob',
            name='e_value_cutoff',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
