# Generated by Django 2.0.3 on 2018-04-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0035_auto_20180419_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bammscanjob',
            name='m_Fold',
            field=models.IntegerField(default=1),
        ),
    ]
