# Generated by Django 2.0.3 on 2018-04-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0036_auto_20180421_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbparameter',
            name='experiment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dbparameter',
            name='species',
            field=models.CharField(max_length=100),
        ),
    ]
