# Generated by Django 2.0.3 on 2018-04-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0037_auto_20180421_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipseq',
            name='cell_type',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
