# Generated by Django 2.0.3 on 2018-05-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0039_auto_20180503_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bammjob',
            name='Motif_Init_File_Format',
            field=models.CharField(choices=[('MEME', 'MEME'), ('BaMM', 'BaMM')], default='BaMM', max_length=255),
        ),
        migrations.AlterField(
            model_name='onestepbammjob',
            name='Motif_Init_File_Format',
            field=models.CharField(choices=[('MEME', 'MEME'), ('BaMM', 'BaMM')], default='BaMM', max_length=255),
        ),
    ]
