# Generated by Django 2.0.3 on 2018-05-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0041_remove_bammjob_bgmodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onestepbammjob',
            name='bgModel_File',
        ),
    ]
