# Generated by Django 2.0.5 on 2018-05-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0043_auto_20180503_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bammjob',
            name='m_Fold',
            field=models.IntegerField(default=1),
        ),
    ]
