# Generated by Django 2.0.5 on 2018-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0044_auto_20180509_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onestepbammjob',
            name='m_Fold',
            field=models.IntegerField(default=1),
        ),
    ]
