# Generated by Django 2.0.5 on 2018-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0045_auto_20180511_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='is_example',
            field=models.BooleanField(default=False),
        ),
    ]
