# Generated by Django 2.0.5 on 2018-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bammmotif', '0046_jobinfo_is_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='bammjob',
            name='has_bedfile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bammscanjob',
            name='has_bedfile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onestepbammjob',
            name='has_bedfile',
            field=models.BooleanField(default=False),
        ),
    ]
